/* Arthor: Louis He
 * Year: 2020
 *
 * This file is for acedemic training purpose only. Do NOT distribute this file without the consent of the arthor.
 * 
 * Please DO NOT EDIT THIS FILE. All the changes you need to do is in file sample.c and sample.h
 */

#include <iostream>

extern "C" {
#include "sample.h"
}

int main(int argc, char* argv[]) {
    int test_num;
    std::cin >> test_num;
    std::cout << "=== Test Number: " << test_num << " ===" << std::endl;
    for (int i = 0; i < test_num; i++) {
        int test_check;
        std::cin >> test_check;

        try {
            if (test_check != (i + 1)) {
                std::cerr << "\033[31mRead input file error, sanity check failed. Occured at case #" << i + 1 << "\033[0m\n";
                break;
            }
        } catch (const std::exception& e) {
            std::cerr << "\033[31mRead input file error, critical error. Occured at case #" << i + 1 << "\033[0m\n";
        }
        std::cout << "=== Case #" << i + 1 << " ===" << std::endl;
        if (i < 5) {
            hello1();
        } else {
            hello2();
        }

        std::cout << "\n=== END ===" << std::endl;
    }
    return 0;
}
